AudioQuiz/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('staticpages.urls')),
    path('classes/', include('classes.urls')),
    path('accounts/', include('accounts.urls')), 
    path('accounts/', include('django.contrib.auth.urls')), 
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import registro_view, ListaAlunosView

app_name = 'accounts'
urlpatterns = [
    path('profile', views.ProfileView.as_view(), name='profile'),
    path('profile/atualizar/', views.atualizar_perfil, name='atualizar_perfil'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="/"), name='logout'),
    path('signup/', views.registro_view, name='signup'),
    path('alunos/', views.ListaAlunosView.as_view(), name='lista_alunos')
]

classes/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'classes'
urlpatterns = [
    path('', views.ClasseListView.as_view(), name='index'),
    path('<int:pk>/', views.ClasseMuralView.as_view(), name='mural'),
    path('<int:pk>/flashcards', views.ClasseFlashcardsView.as_view(), name='flashcards'),
    path('<int:pk>/create_flashcards', views.ClasseFlashcardsCreate.as_view(), name='create_flashcards'),
    path('<int:pk>/delete_flashcards/<int:deck_id>/', views.ClasseFlashcardsDelete.as_view(), name='delete_flashcards'),
    path('<int:deck_id>/cards/<int:pk>/', views.CardDetailView.as_view(), name='cards'),
    path('<int:deck_id>/cards/<int:pk>/marcar-maduro/', views.marcar_maduro_proximo, name='maduroeproximo'),
    path('<int:deck_id>/cards/<int:pk>/desmarcar-maduro/', views.desmarcar_maduro_proximo, name='naomaduroeproximo'),
    path('<int:deck_id>/cards/new/', views.CardCreateView.as_view(), name='create_card'),
    path('deck/<int:deck_id>/cards/', views.CardsInDeckListView.as_view(), name='cards_in_deck'),
    path('<int:deck_id>/cards/<int:card_id>/deletar/', views.CardDeleteView.as_view(), name='delete_card'),
    path('<int:deck_id>/cards/<int:pk>/editar/', views.CardUpdateView.as_view(), name='update_card'),
    path('create/', views.ClasseCreateView.as_view(), name='create'),
    path('<int:pk>/mensagem/', views.MensagemCreateView.as_view(), name='mensagem'),
    path('<int:pk>/mensagem/responder/<int:resposta_id>/', views.MensagemCreateView.as_view(), name='responder_mensagem'),
    path('<int:pk>/mensagem/delete/<int:mensagem_id>/', views.MensagemDeleteView.as_view(), name='delete_message'),
    path('delete/<int:pk>/', views.ClasseDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', views.ClasseUpdateView.as_view(), name='update'),
    path('download/<int:pk>/', views.download_pdf, name='download_pdf'),
    path('aceitar_convite/<int:notificacao_id>/', views.aceitar_convite, name='aceitar_convite'),
    path('recursar_convite/<int:notificacao_id>/', views.recusar_convite, name='recusar_convite'),
    path('<int:pk>/atividades', views.ClasseAtividadesView.as_view(), name='atividades_index'),
    path('<int:pk>/atividades/upload', views.AtividadeCreateView.as_view(), name='atividades_create'),
    path('<int:pk>/atividades/delete', views.AtividadeDeleteView.as_view(), name='atividades_delete'),
    path('<int:pk>/atividades/update', views.AtividadeUpdateView.as_view(), name='atividades_update'),
    path('api/transcribe_audio/', views.transcribe_audio, name='transcribe_audio'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classes/models.py
from django.db import models
from accounts.models import Usuario
from django.utils.timezone import now

class Classe(models.Model):
    turma = models.CharField(max_length=255)
    idioma = models.CharField(max_length=255)
    poster = models.ImageField(upload_to='classes/', blank=True, null=True)
    usuarios = models.ManyToManyField(Usuario)

    def __str__(self):
        return self.turma
    
    @property
    def poster_url(self):
        """Retorna a URL do poster ou uma imagem padrão."""
        if self.poster:
            return self.poster.url
        return '/static/images/Japan.svg'  # Substitua pelo caminho correto para sua imagem padrão

class Notificacao(models.Model):
    titulo = models.CharField(max_length=255)
    mensagem = models.TextField()
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    data_criacao = models.DateTimeField(default=now)
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE, null=True, blank=True)  # Relaciona à classe, se aplicável
    lida = models.BooleanField(default=False)  # Para marcar se o usuário já viu a notificação

    def __str__(self):
        return f"Notificação para {self.usuario.username}: {self.titulo}"
    
class Deck(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE)
    nome = models.CharField(max_length=255)
    idioma = models.CharField(max_length=255)
    
    @property
    def n_dominados(self):
        return self.card_set.filter(maduro=True).count()

    @property
    def n_cartoes(self):
        return self.card_set.count()


    @property
    def n_aprender(self):
        return self.n_cartoes - self.n_dominados

    def __str__(self):
        return self.nome


class Card(models.Model):
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE, )
    lado_frente = models.CharField(max_length=255)
    lado_tras = models.CharField(max_length=255)
    dica_1 = models.CharField(max_length=255, blank=True, null=True)
    dica_2 = models.CharField(max_length=255, blank=True, null=True)
    dica_3 = models.CharField(max_length=255, blank=True, null=True)
    n_revisoes = models.IntegerField(default=0)
    maduro = models.BooleanField(default=False)
    data_criacao = models.DateTimeField(auto_now_add=True)
    data_ultima_revisao = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.lado_frente

class Mensagem(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE, related_name='mensagens' )
    conteudo = models.TextField(max_length=1000)
    data_envio = models.DateTimeField(auto_now_add=True)
    resposta_para = models.ForeignKey(
        'self',  # Faz referência ao próprio modelo
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='respostas'  # Permite acessar as respostas de uma mensagem
    )

    def __str__(self):
        return f"Mensagem de {self.usuario}"
    
class Arquivo(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE)
    nome = models.CharField(max_length=255)  # Nome do arquivo
    tipo = models.CharField(max_length=50, default='PDF')  # Tipo do arquivo (ex: application/pdf)
    conteudo = models.BinaryField(default=b'')# Armazena o conteúdo binário do arquivo
    data_upload = models.DateTimeField(auto_now_add=True, null=True)  # Data de envio

    def __str__(self):
        return self.nome

classes/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.conf import settings
from datetime import datetime
import os, shutil
from django.views.generic import TemplateView, View
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.contrib.auth import login
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import  Notificacao, Classe, Deck, Card, Mensagem, Arquivo
from .forms import ClasseForm, ArquivoForm, DeckForm, CardForm, MensagemForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils.safestring import mark_safe
import json
from django.http import JsonResponse
from django.utils.timezone import now
import os
import speech_recognition as sr
from django.views.decorators.csrf import csrf_exempt
from pydub import AudioSegment
from pydub.utils import which
import logging
import os
import sounddevice as sd
import numpy as np
import wave
import logging
from pydub import AudioSegment
import speech_recognition as sr
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import subprocess

class ClasseListView(ListView):
    model = Classe
    template_name = 'classes/index.html'

class ClasseDeleteView(DeleteView):
    model = Classe
    template_name = 'classes/delete.html'
    success_url = reverse_lazy('classes:index')

class ClasseUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Classe
    form_class = ClasseForm
    template_name = 'classes/update.html'
    success_url = reverse_lazy('classes:index')

    def form_valid(self, form):
        classe = form.save(commit=False)
        classe.save()
        form.save_m2m()  # Salvar alunos selecionados
        # Verifica novos alunos para evitar notificações duplicadas
        novos_alunos = form.cleaned_data['alunos'].exclude(id__in=classe.usuarios.all())
        classe.usuarios.add(self.request.user)  # Adiciona o professor à classe
        self.enviar_notificacao_para_alunos(novos_alunos, classe)
        return super().form_valid(form)

    def enviar_notificacao_para_alunos(self, novos_alunos, classe):
        """Envia notificações apenas para novos alunos convidados"""
        for aluno in novos_alunos:
            Notificacao.objects.create(
                titulo="Convite para a classe",
                mensagem=f"Você foi convidado para a classe '{classe.turma}' de {classe.idioma}.",
                classe=classe,
                usuario=aluno
            )
    def test_func(self):
        # Permitir acesso apenas para professores
        return self.request.user.is_authenticated and self.request.user.tipo == 1

class MensagemDeleteView(DeleteView):
    model = Mensagem
    template_name = 'classes/mural/delete.html'

    def get_object(self, queryset=None):
        # Recupera o objeto Mensagem usando o mensagem_id
        mensagem_id = self.kwargs.get('mensagem_id')
        return get_object_or_404(Mensagem, pk=mensagem_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Adiciona o objeto Classe ao contexto
        context['Classe'] = get_object_or_404(Classe, pk=self.kwargs['pk'])
        return context

    def get_success_url(self):
        # Redireciona de volta para o mural da classe
        return reverse_lazy('classes:mural', kwargs={'pk': self.kwargs['pk']})

class ClasseMuralView(View):
    def get(self, request, pk):
        classe = get_object_or_404(Classe, pk=pk)
        mensagens = classe.mensagens.filter(resposta_para__isnull=True)  # Apenas mensagens principais
        return render(request, 'classes/mural/index.html', {'Classe': classe, 'mensagens': mensagens})

class ClasseAtividadesView(DetailView):
    model = Classe
    template_name = 'classes/atividades/index.html'
    context_object_name = 'Classe'

class AtividadeCreateView(View):
    def get(self, request, pk):
        classe = get_object_or_404(Classe, pk=pk)# Garante que a Classe existe
        form = ArquivoForm()
        return render(request, 'classes/atividades/atividade.html', {'form': form, 'Classe': classe})

    def post(self, request, pk):
        classe = get_object_or_404(Classe, pk=pk)
        form = ArquivoForm(request.POST, request.FILES)
        if form.is_valid():
            arquivo = form.save(commit=False)
            arquivo.classe = classe
            arquivo.usuario = request.user  # Associa o usuário autenticado
            arquivo.tipo = request.FILES['conteudo'].content_type
            arquivo.conteudo = request.FILES['conteudo'].read()
            arquivo.save()
            return HttpResponseRedirect(reverse_lazy('classes:atividades_index', kwargs={'pk': pk}))
        return render(request, 'classes/atividades/atividade.html', {'form': form, 'Classe': classe})

class AtividadeDeleteView(DeleteView):
    model = Arquivo  # Corrige para deletar o modelo Arquivo (atividade)
    template_name = 'classes/atividades/delete.html'
    
    def get_success_url(self):
        # Retorna para a lista de atividades da classe após a exclusão
        return reverse_lazy('classes:atividades_index', kwargs={'pk': self.object.classe.id})

class AtividadeUpdateView(View):
    def get(self, request, pk):
        # Recupera a atividade pelo ID
        atividade = get_object_or_404(Arquivo, pk=pk)
        form = ArquivoForm(instance=atividade)  # Preenche o formulário com os dados da atividade existente
        return render(request, 'classes/atividades/update.html', {'form': form, 'atividade': atividade})

    def post(self, request, pk):
        # Recupera a atividade pelo ID
        atividade = get_object_or_404(Arquivo, pk=pk)
        form = ArquivoForm(request.POST, request.FILES, instance=atividade)  # Associa o formulário à atividade
        if form.is_valid():
            arquivo = form.save(commit=False)
            
            # Verifica se um novo arquivo foi enviado
            if 'conteudo' in request.FILES:
                arquivo.tipo = request.FILES['conteudo'].content_type
                arquivo.conteudo = request.FILES['conteudo'].read()

            arquivo.save()  # Salva as alterações na atividade
            return HttpResponseRedirect(reverse_lazy('classes:atividades_index', kwargs={'pk': atividade.classe.pk}))

        return render(request, 'classes/atividades/update.html', {'form': form, 'atividade': atividade})

def download_pdf(request, pk):
    # Recupera o arquivo pelo ID
    arquivo = get_object_or_404(Arquivo, pk=pk)

    try:
        # Retorna o conteúdo binário como resposta para download
        response = HttpResponse(arquivo.conteudo, content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{arquivo.nome}.pdf"'
        return response
    except Exception as e:
        raise Http404("Erro ao processar o arquivo")

class ClasseFlashcardsView(DetailView):
    model = Classe
    template_name = 'classes/flashcards/index.html'
    context_object_name = 'Classe'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        classe = self.object  # A classe atual (detalhe sendo exibido)

        # Adiciona a Classe ao contexto
        context['Classe'] = classe

        # Filtra decks associados à classe, ao usuário logado e ao tipo de usuário
        if self.request.user.tipo == 0:  # Garante que o filtro é feito apenas para tipo 0
            context['Deck_list'] = Deck.objects.filter(classe=classe, usuario=self.request.user)
        else:
            context['Deck_list'] = Deck.objects.filter(classe=classe)  # Nenhum deck se o tipo não for 0

        return context

class ClasseFlashcardsCreate(CreateView):
    model = Deck
    form_class = DeckForm
    template_name = 'classes/flashcards/create.html'

    def form_valid(self, form):
        """
        Define a classe e o usuário associados ao deck e salva.
        """
        classe = get_object_or_404(Classe, pk=self.kwargs['pk'])
        form.instance.classe = classe
        form.instance.usuario = self.request.user
        self.object = form.save()  # Salva e armazena o objeto criado
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Classe'] = get_object_or_404(Classe, pk=self.kwargs['pk'])
        return context

    def get_success_url(self):
        """
        Redireciona para a página de flashcards da classe.
        """
        return reverse_lazy('classes:flashcards', kwargs={'pk': self.object.classe.pk})
    
class ClasseFlashcardsDelete(DeleteView):
    model = Deck
    template_name = 'classes/flashcards/delete.html'

    def get_object(self, queryset=None):
        print(f"Classe ID: {self.kwargs['pk']}, Deck ID: {self.kwargs['deck_id']}")
        return get_object_or_404(Deck, pk=self.kwargs['deck_id'], classe_id=self.kwargs['pk'])

    def get_success_url(self):
        # Redireciona para a lista de flashcards após a exclusão
        return reverse_lazy('classes:flashcards', kwargs={'pk': self.kwargs['pk']})
    
class CardCreateView(CreateView):
    model = Card
    form_class = CardForm
    template_name = 'classes/flashcards/cards/create.html'

    def form_valid(self, form):

classes/templates/classes/create.html
{% extends 'base.html' %} {% block content %}
{% if user.is_authenticated %}
<div Class="page-form">
  <h2>Nova Classe</h2>
  <hr class="page-break">
  <form method="POST" action="{% url 'classes:create' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="botaozinho">Criar</button>
    <a href="{% url 'classes:index' %}" class = 'botaozinho'>Voltar</a>
  </form>
</div>
{% else %}
  <p>Você não está logado.</p>
  <br>
  <a href="{% url 'accounts:login' %}" class="botaozinho">Faça login aqui</a>
{% endif %}
{% endblock content %}

classes/templates/classes/delete.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}

<form action="{% url 'classes:delete' classe.id %}" method="post">
  {% csrf_token %}
  <h2>
    Você tem certeza que deseja apagar a classe: {{ classe.idioma }} - Turma {{ classe.turma }}?
  </h2>
  <br>
  <button type="submit" class = "delete-button">Apagar</button>
  <a href="{% url 'classes:index'%}" class = "botaozinho">Voltar</a>
</form>

{% else %}
  <p>Você não está logado.</p>
  <br>
  <a href="{% url 'accounts:login' %}" class="botaozinho">Faça login aqui</a>
{% endif %}
{% endblock content %}

classes/templates/classes/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  {% if user.is_authenticated %}

    <h1>Classes</h1>
    <hr class="page-break">
    <h2>Seja bem-vindo, {{ user.first_name }}</h2>
    
    <!-- Notificações para o aluno -->
    {% if user.tipo == 0 and user.notificacao_set.all %}
      <section class="notificacoes">
        <br>
        
          <h3>Notificações</h3> 
          {% for notificacao in user.notificacao_set.all %}
            {% if not notificacao.lida %}
            <ul style="list-style: none;">
              <li>
                <h4>{{ notificacao.titulo }}</h4>
                <p>{{ notificacao.mensagem }}</p>
                <br>
                <div class="acoes">
                  <a href="{% url 'classes:aceitar_convite' notificacao.id %}" class="aceitar">
                    Aceitar Convite
                  </a>
                  <a href="{% url 'classes:recusar_convite' notificacao.id %}" class="recusar">
                    Recusar Convite
                  </a>
                </div>
              </li>
            {% endif %}
          {% endfor %}
        </ul>
      </section>
    {% endif %}

    <!-- Listagem de Classes -->
      <section class="lista-de-cards">
        {% for Classe in user.classe_set.all %}
          <article class="card">
            <a href="{% url 'classes:mural' Classe.id %}">
              <img src="{{ Classe.poster_url }}" alt="Poster do {{ Classe.idioma }}" />
            </a>
            <p><strong>{{ Classe.idioma }}</strong></p>
            <p>Turma {{ Classe.turma }}</p>
            
            <!-- Professores -->
            {% for Usuario in Classe.usuarios.all %}
              {% if Usuario.tipo == 1 %}
                <p>Professor {{ Usuario.first_name }} {{ Usuario.last_name }}</p>
              {% endif %}
            {% endfor %}
            
            <!-- Ações para Professores -->
            {% if user.tipo == 1 %}
              <div class="acoes">
                <a href="{% url 'classes:update' Classe.id %}" class="editar">Editar Classe</a>
                <a href="{% url 'classes:delete' Classe.id %}" class="apagar">Apagar Classe</a>
              </div>
            {% endif %}
          </article>
        {% endfor %}
        {% if user.tipo == 0 %}
          {% if user.classe_set.all %}
          {% else%}
          <br>
          <p>Você não está matriculado em nenhuma classe.</p>
          {% endif %}
        {% endif %}
        <!-- Botão de Criar Nova Classe -->
        {% if user.tipo == 1 %}
          <article class="card">
            <a href="{% url 'classes:create' %}">
              <div class="card-image-wrapper">
                <img src="{% static 'Plus square 1.png' %}" alt="Imagem adicionar classe" />
              </div>
              <div class="card-content">
                <p><strong>Criar nova classe</strong></p>
              </div>
            </a>
          </article>
        {% endif %}
      </section>
    

  {% else %}
    <p>Você não está logado.</p>
    <br>
    <a href="{% url 'accounts:login' %}" class="botaozinho">Faça login aqui</a>
  {% endif %}
{% endblock content %}

classes/templates/classes/update.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="page-form">
  <h2>Alterar Classe {{Classe.turma}}</h2>
  <hr Class="page-break">
  <form method="POST" action="{% url 'classes:update' classe.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="botaozinho">Alterar</button>
    <a href="{% url 'classes:index' %}" class = 'botaozinho'>Voltar</a>
  </form>
</div>
{% else %}
  <p>Você não está logado.</p>
  <br>
  <a href="{% url 'accounts:login' %}" class="botaozinho">Faça login aqui</a>
{% endif %}
{% endblock content %}